language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
before_install:
  - sudo apt-get install festival festvox-kallpc16k
  - sudo apt-get update
  - sudo apt-get install libav-tools
  - sudo apt-get update
  - sudo apt-get install ffmpeg
