language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
before_install:
  - sudo echo deb http://www.deb-multimedia.org testing main non-free >>/etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install deb-multimedia-keyring
  - sudo apt-get update
  - sudo apt-get install ffmpeg
